package flappy.db;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import org.hsqldb.Server;
import org.hsqldb.persist.HsqlProperties;
import org.hsqldb.server.ServerAcl.AclFormatException;

public class ScoreDB {

	Connection conn = null;
	Statement stmt;

	public ScoreDB() {

		HsqlProperties hsqlProperties = new HsqlProperties();
		hsqlProperties.setProperty("server.database.0",
		"db\\FlappyDB");

		hsqlProperties.setProperty("server.dbname.0", "mdb");
		Server server = new Server();
		try {
			server.setProperties(hsqlProperties);

		} catch (IOException | AclFormatException e) {
			e.printStackTrace();
		}
		server.setTrace(true);
		server.start();
		
		try {
			conn = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/mdb", "SA", "");
			stmt = conn.createStatement();
			stmt.executeQuery("CREATE TABLE IF NOT EXISTS Puntuaciones (\r\n" + 
					" IDJugador INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),\r\n" + 
					" Nombre VARCHAR(30) NOT NULL, \r\n" + 
					" Puntos INTEGER NOT NULL,\r\n" + 
					" PRIMARY KEY (IDJugador)\r\n" + 
					");\r\n" + 
					"");
			stmt.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public Connection getConexion() {
		return conn;
	}

	public void closeConexion() {
		try {
			stmt = conn.createStatement();
			stmt.executeQuery("SHUTDOWN COMPACT");
			stmt.close();
			conn.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
