INSERT INTO puntuaciones VALUES (DEFAULT, 'Ruben', 23);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Rafael', 45);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Manuel', 13);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Kjaer', 4);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Jorge', 2);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Marcos', 34);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Fernican', 69);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Tortolo', 40);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Mary', 17);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Josh', 50);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Reynaldo', 41);
INSERT INTO puntuaciones VALUES (DEFAULT, 'Ze Carlos', 33);
